vich_uploader:
    db_driver: orm

    mappings:
        coverFile:
            uri_prefix: /medias/images/books/covers
            upload_destination: '%kernel.project_dir%/public/medias/images/books/covers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        file:
            uri_prefix: /medias/images/resources
            upload_destination: '%kernel.project_dir%/public/medias/images/resources'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer